### PR TITLE
properly initialize UTF8 strings

### LINKED ISSUE #11: Junk in strings (uninitialized?)
изображение
изображение

### PR DESCRIPTION
**Pull request by DasMaddi**
Thanks to Nbc66 and friends for catching this. Fixes #11

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
This seems unnecessary, we should only need to null terminate at [nChars] after the V_BlahToUTF8

**Comment by DasMaddi** [comment]
To be quite honest I did not encounter any issues with junk strings during testing and dev, so I wasn't able to repro this. I can adjust as needed.

**Comment by nillerusr** [comment]
@DasMaddi bug is still present. 
image

As @Joshua-Ashton mentioned array initialization is unnecessary. 
The real problem is here: 
```c++
int nChars = V_UTF8ToUnicode( pszText, szUnicode, sizeof( szUnicode ) );
```
V_UTF8ToUnicode returns size in bytes

**Comment by misyltoad** [comment]
Please make an MR

**Pull request merged**
